name: Build and Deploy Portfolio

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OpenVPN and Network Tools
        run: |
          sudo apt update
          sudo apt install -y openvpn resolvconf bridge-utils isc-dhcp-client

      - name: Setup VPN config
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > config.ovpn
          echo "${{ secrets.OVPN_USERNAME }}" > auth.txt
          echo "${{ secrets.OVPN_PASSWORD }}" >> auth.txt
          sudo chmod 600 config.ovpn auth.txt

      - name: Connect to VPN
        run: |
          # Créer l'interface TAP
          sudo ip tuntap add dev tap0 mode tap
          sudo ip link set tap0 up

          # Démarrer OpenVPN
          sudo openvpn --config config.ovpn --auth-user-pass auth.txt --daemon --verb 4

          # Attendre que la connexion s'établisse
          sleep 15

          # Demander une adresse IP via DHCP
          sudo dhclient tap0

          # Vérifier la configuration obtenue
          echo "=== Configuration IP ==="
          ip addr show tap0
          echo "=== Routes ===="
          ip route

      - name: Test VPN Connection
        run: |
          echo "=== Interface réseau ==="
          ip addr
          echo "=== Table de routage ==="
          ip route
          echo "=== Test rasp5 ==="
          ping -c 4 192.168.1.17
          echo "=== Test Nomad ==="
          curl -v http://192.168.1.17:4646

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Nomad
        env:
          NOMAD_ADDR: http://192.168.1.17:4646
        run: |
          curl -L -o nomad.zip https://releases.hashicorp.com/nomad/1.9.5/nomad_1.9.5_linux_amd64.zip
          unzip nomad.zip
          ./nomad job run -var="image=ghcr.io/${{ github.repository }}:latest" portfolio.nomad

      - name: Cleanup VPN
        if: always()
        run: |
          # Restaurer la route par défaut originale si présente
          sudo ip route add default via 10.1.0.1 dev eth0 || true
          sudo pkill openvpn || true
          rm -f config.ovpn auth.txt
