name: Deploy Next.js App to Raspberry Pi

on:
  push:
    branches:
      - main  # Déclencher le workflow à chaque push sur la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code du dépôt GitHub dans l'environnement GitHub Actions
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Se connecter au Raspberry Pi via SSH et exécuter les commandes
      - name: Build and deploy on Raspberry Pi
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: |
            cd /home/sny1411

            # Si le projet n'existe pas, cloner le dépôt
            if [ ! -d "nextjs-app" ]; then
              git clone git@github.com:sny1411/nextjs-portfolio.git nextjs-app
            fi

            # Naviguer vers le répertoire du projet
            cd nextjs-app

            # Récupérer les dernières modifications du dépôt
            git pull origin main

            # Arrêter le conteneur s'il est déjà en cours d'exécution
            sudo docker stop nextjs-app || true

            # Supprimer l'ancien conteneur
            sudo docker rm nextjs-app || true

            # Construire l'image Docker sur le Raspberry Pi
            sudo docker build -t nextjs-portfolio-pnpm .

            # Démarrer le nouveau conteneur
            sudo docker run -d -p 3000:3000 --name nextjs-app nextjs-portfolio-pnpm
