name: Build and Deploy Portfolio
on:
  push:
    branches: [ main ]

permissions:
  contents: read    # Permet de lire le contenu du dépôt
  packages: write   # Permet de pousser des packages dans GHCR
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Verify OpenVPN Version
        run: openvpn --version

      - name: Setup VPN Authentication File
        run: |
          echo "${{ secrets.OVPN_USERNAME }}" > auth.txt
          echo "${{ secrets.OVPN_PASSWORD }}" >> auth.txt
          chmod 600 auth.txt

      - name: Setup VPN
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > config.ovpn
          echo "auth-user-pass auth.txt" >> config.ovpn
          sudo openvpn --config config.ovpn --daemon --verb 4
          sleep 10  # Attendre que la connexion soit établie
          sudo cat /var/log/syslog | grep openvpn  # Afficher les logs OpenVPN   

      - name: Test VPN connection
        run: |
          curl -v http://192.168.1.17:4646  # Vérifier si le serveur Nomad est accessible via le VPN

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Nomad
        env:
          NOMAD_ADDR: http://192.168.1.17:4646
        run: |
          curl -L -o nomad.zip https://releases.hashicorp.com/nomad/1.9.5/nomad_1.9.5_linux_amd64.zip
          unzip nomad.zip
          ./nomad job run -var="image=ghcr.io/${{ github.repository }}:latest" portfolio.nomad
