name: Deploy to Nomad

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nomad CLI
        run: |
          curl -L -o nomad.zip https://releases.hashicorp.com/nomad/1.9.5/nomad_1.9.5_linux_amd64.zip
          unzip -o nomad.zip -d /usr/local/bin
          rm nomad.zip

      - name: Deploy Job to Nomad
        env:
          NOMAD_ADDR: http://192.168.1.17:4646
        run: |
          nomad job run \
            -var="image=192.168.1.13:5000/portfolio:latest" \
            portfolio.nomad
