name: Deploy to Nomad

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nomad
        run: |
          curl -L -o nomad.zip https://releases.hashicorp.com/nomad/1.9.5/nomad_1.9.5_linux_amd64.zip
          unzip nomad.zip -d nomad-temp
          sudo install -m 0755 nomad-temp/nomad /usr/local/bin/nomad
          rm -rf nomad.zip nomad-temp

      - name: Deploy Job to Nomad
        env:
          NOMAD_ADDR: http://192.168.1.17:4646
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          nomad job run portfolio.nomad
