name: Build and Deploy Portfolio
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install OpenVPN 2
        run: |
          sudo apt-get update
          sudo apt-get remove -y openvpn  # Supprime la version existante
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:openvpn/stable
          sudo apt-get update
          sudo apt-get install -y openvpn=2.*  # Installe OpenVPN 2

      - name: Setup VPN Authentication File
        run: |
          echo "${{ secrets.OVPN_USERNAME }}" > auth.txt
          echo "${{ secrets.OVPN_PASSWORD }}" >> auth.txt
          chmod 600 auth.txt

      - name: Setup VPN
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > config.ovpn
          echo "auth-user-pass auth.txt" >> config.ovpn
          sudo openvpn --config config.ovpn --daemon
          sleep 10  # Attendre que la connexion soit établie

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Nomad
        env:
          NOMAD_ADDR: http://192.168.1.17:4646
        run: |
          curl -L -o nomad.zip https://releases.hashicorp.com/nomad/1.9.5/nomad_1.9.5_linux_amd64.zip
          unzip nomad.zip
          ./nomad job run -var="image=ghcr.io/${{ github.repository }}:latest" portfolio.nomad
