name: Build and Deploy Portfolio

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OpenVPN and Network Tools
        run: |
          sudo apt update
          sudo apt install -y openvpn resolvconf net-tools traceroute

      - name: Setup VPN config
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > config.ovpn
          echo "${{ secrets.OVPN_USERNAME }}" > auth.txt
          echo "${{ secrets.OVPN_PASSWORD }}" >> auth.txt
          sudo chmod 600 config.ovpn auth.txt

      - name: Connect to VPN and Configure Network
        run: |
          echo "=== Démarrage OpenVPN ==="
          sudo openvpn --config config.ovpn --auth-user-pass auth.txt --daemon
          sleep 15
          
          echo "=== Vérification de l'état OpenVPN ==="
          if ! pgrep openvpn; then
            echo "Échec du démarrage d'OpenVPN"
            sudo journalctl -u openvpn | tail -n 20
            exit 1
          fi
          
          echo "=== Vérification de l'interface TAP ==="
          VPN_INTERFACE=$(ip -o link show | grep tap0 | awk -F': ' '{print $2}')
          if [ -z "$VPN_INTERFACE" ]; then
            echo "Aucune interface TAP détectée. Vérifiez la configuration."
            exit 1
          fi
          
          echo "Interface VPN détectée: $VPN_INTERFACE"
          sudo ip link set "$VPN_INTERFACE" up
          sudo ip addr add 192.168.1.100/24 dev "$VPN_INTERFACE" || true
          
          echo "=== Informations réseau ==="
          ip addr show "$VPN_INTERFACE"
          
          echo "=== Test de connectivité ==="
          traceroute 192.168.1.17 || echo "Problème de routage"
          ping -c 3 192.168.1.17 || echo "Problème de connexion au serveur"

      - name: Check VPN Connection
        run: |
          echo "Test de connexion au serveur Nomad:"
          curl -v --connect-timeout 10 http://192.168.1.17:4646 || exit 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Nomad
        env:
          NOMAD_ADDR: http://192.168.1.17:4646
        run: |
          curl -L -o nomad.zip https://releases.hashicorp.com/nomad/1.9.5/nomad_1.9.5_linux_amd64.zip
          unzip nomad.zip
          ./nomad job run \
          -var="image=ghcr.io/${{ github.repository }}:latest" \
          portfolio.nomad

      - name: Cleanup VPN
        if: always()
        run: |
          # Restaurer la route par défaut originale si présente
          sudo ip route add default via 10.1.0.1 dev eth0 || true
          sudo pkill openvpn || true
          rm -f config.ovpn auth.txt
