name: Deploy Next.js App to Raspberry Pi

on:
  push:
    branches:
      - main  # Déclencher le workflow à chaque push sur la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code du dépôt GitHub
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Installer Docker CLI pour builder l'image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. Builder l'image Docker avec pnpm
      - name: Build Docker image
        run: docker build -t nextjs-portfolio-pnpm .

      # 4. Déployer l'image sur le Raspberry Pi via SSH
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.RPI_HOST }}  # L'adresse IP du Raspberry Pi (définie dans les secrets GitHub)
          username: ${{ secrets.RPI_USER }}  # Le nom d'utilisateur SSH (ex. 'pi')
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # La clé privée SSH (définie dans les secrets)
          port: ${{ secrets.RPI_PORT }}  # Utiliser le port SSH défini dans le secret GitHub
          script: |
            sudo docker stop nextjs-app || true  # Arrêter le conteneur s'il est déjà en cours d'exécution
            sudo docker rm nextjs-app || true    # Supprimer l'ancien conteneur
            sudo docker pull nextjs-portfolio-pnpm  # Récupérer la dernière image Docker
            sudo docker run -d -p 3000:3000 --name nextjs-app nextjs-portfolio-pnpm  # Démarrer le nouveau conteneur
